export const COLUMN_DEFINITIONS = {
  IDENTIFICATION: [
    { key: 'no', label: 'No', width: 'w-16' },
    { key: 'tujuan', label: 'Tujuan / Sasaran' },
    { key: 'indikator', label: 'Indikator Kinerja' },
    { key: 'uraian', label: 'Risiko (Uraian)' },
    { key: 'kode', label: 'Risiko (Kode)' },
    { key: 'pemilik', label: 'Pemilik' },
    { key: 'sebab', label: 'Sebab (Uraian)' },
    { key: 'sebabSumber', label: 'Sebab (Sumber)' },
    { key: 'control', label: 'Control (C/UC)' },
    { key: 'dampak', label: 'Dampak (Akibat)' },
    { key: 'dampakPihak', label: 'Dampak (Pihak)' },
  ],
  ANALYSIS: [
    { key: 'no', label: 'No', width: 'w-16' },
    { key: 'risiko', label: 'Analisis Risiko Teridentifikasi' },
    { key: 'dampak', label: 'Impact Avg' },
    { key: 'probabilitas', label: 'Prob Avg' },
    { key: 'score', label: 'Score (DxS)' },
    { key: 'level', label: 'Level' },
  ],
  EVALUATION: [
    { key: 'no', label: 'No', width: 'w-16' },
    { key: 'risiko', label: 'Risiko Teridentifikasi' },
    { key: 'awal', label: 'Risiko Awal' },
    { key: 'pengendalian', label: 'Pengendalian Saat Ini' },
    { key: 'celah', label: 'Celah (Gap)' },
    { key: 'sisa', label: 'Risiko Sisa (Residual)' },
  ],
  RTP: [
    { key: 'no', label: 'No', width: 'w-16' },
    { key: 'risiko', label: 'Risiko (Residual)' },
    { key: 'pengendalian', label: 'Pengendalian Sisa' },
    { key: 'rtp', label: 'Rencana Tindak (RTP) Baru' },
    { key: 'pj', label: 'Penanggung Jawab' },
    { key: 'deadline', label: 'Deadline' },
  ],
  COMMUNICATION: [
    { key: 'no', label: 'No', width: 'w-16' },
    { key: 'kegiatan', label: 'Kegiatan Pengendalian' },
    { key: 'media', label: 'Media' },
    { key: 'penyedia', label: 'Penyedia Informasi' },
    { key: 'penerima', label: 'Penerima Informasi' },
    { key: 'waktu', label: 'Rencana Waktu' },
  ],
  MONITORING: [
    { key: 'no', label: 'No', width: 'w-16' },
    { key: 'kegiatan', label: 'Kegiatan Pengendalian' },
    { key: 'metode', label: 'Bentuk/Metode Pemantauan' },
    { key: 'pj', label: 'Penanggung Jawab' },
    { key: 'waktu', label: 'Rencana Waktu' },
  ],
  LOG: [
    { key: 'no', label: 'No', width: 'w-16' },
    { key: 'risiko', label: 'Risiko Teridentifikasi' },
    { key: 'kode', label: 'Kode' },
    { key: 'tanggal', label: 'Tanggal Kejadian' },
    { key: 'sebab', label: 'Sebab Actual' },
    { key: 'dampak', label: 'Dampak Actual' },
    { key: 'rtp', label: 'RTP' },
  ]
};
